# Dependabot configuration for automatic dependency updates
version: 2
updates:
  # NPM - JavaScript/TypeScript dependencies (Web frontend)
  - package-ecosystem: "npm"
    directory: "/web" 
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      frontend-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # Go Modules - Gateway Service
  - package-ecosystem: "gomod"
    directory: "/gateway-service"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      gateway-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # Go Modules - App Service
  - package-ecosystem: "gomod"
    directory: "/app-service"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      app-service-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # Go Modules - Go Utils (shared package)
  - package-ecosystem: "gomod"
    directory: "/packages/go-utils"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      go-utils-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # Go Modules - Testing Utilities
  - package-ecosystem: "gomod"
    directory: "/testing"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      testing-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # Python - Testing / Backend dependencies
  - package-ecosystem: "pip"
    directory: "/propagator-service"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      python-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # Docker - Updates for Dockerfiles
  - package-ecosystem: "docker"
    directory: "/"  # Root Dockerfile
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      docker-dependencies:
        patterns:
          - "*"
