{
 "title": "Logs",
 "time": { "from": "2025-01-14T20:13:35.554Z", "to": "2025-01-14T22:53:29.246Z" },
 "panels": [
  {
   "title": "Liveness",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "app_liveness", "legendFormat": "__auto" },
    { "expr": "app_uptime_seconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "prometheus_http_request_duration_seconds_bucket",
     "legendFormat": "__auto"
    },
    { "expr": "prometheus_http_requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Logs",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{container_name=\"app-service\"} |= ``"
    }
   ]
  }
 ]
}