# yaml-language-server: $schema=https://raw.githubusercontent.com/deepmap/oapi-codegen/HEAD/configuration-schema.json
package: server
generate:
  models: true
  echo-server: true
  embedded-spec: true
  strict-server: true
