name: Python CI Workflow

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  build-and-test:
    name: Build and Test Python App
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # Cache dependencies
      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Install dependencies (including flake8)
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8  # Ensure flake8 is installed
        working-directory: org/propagator-service

      # Run linting with flake8
      - name: Run flake8 linter
        run: flake8 .
        working-directory: org/propagator-service

      # Run tests with pytest
      - name: Run tests with pytest
        run: pytest
        working-directory: org/propagator-service
