name: Testing Integration Workflow

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  integration-tests:
    name: Run Integration Tests
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Verify Docker installation
      - name: Check Docker version
        run: |
          docker --version
          docker compose version || echo "Docker Compose not installed separately"

      # Install dependencies (Make)
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y make

      # Pull required Docker images
      - name: Pull required Docker images
        run: |
          docker pull postgis/postgis:latest
          docker pull redis:latest
          docker pull rabbitmq:management

      # Create the custom Docker network
      - name: Create Docker network
        run: docker network create 2112_net || echo "Network already exists"

      # Build the Docker images locally using 'org/' as the context
      - name: Build Docker images
        run: |
          docker build -t propagator-service -f ../deployments/docker/Dockerfile.propagator .
        working-directory: org  

      # Run Makefile command to setup integration test environment (Start Containers)
      - name: Set up integration test environment
        run: make test-it-setup-up
        working-directory: org/testing

      # Wait for database and services to be ready
      - name: Wait for services to be ready
        run: sleep 15  

      # Run integration tests
      - name: Run integration tests
        run: make test-it
        working-directory: org/testing

      # Run Cucumber report generation
      - name: Generate Cucumber report
        run: make test-it-report
        working-directory: org/testing

      # Upload artifacts (logs, reports, test results, etc.)
      - name: Upload test artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: integration-test-results
          path: org/testing/integration/_artifacts
          retention-days: 7 

      # Cleanup resources after tests
      - name: Tear down Docker containers
        run: |
          docker stop 2112-database.db test-redis test-rabbitmq || echo "Some containers were not running"
          docker rm 2112-database.db test-redis test-rabbitmq || echo "Some containers were already removed"
          docker network rm 2112_net || echo "Network was already removed"
